### ISSUE TITLE
Bug: Always max defense armor from Perfect rolls doesn't work.

### ISSUE THREAD

**Issue by host1126** [mapron/d2modgen#14]
hello. Thanks for making a great tool.
I am using version 0.5.6 and Always max defense armor is not working properly.

**Comment by mapron** [comment]
Can you give an example ?

**Comment by mapron** [comment]
I just generated with this option checked, 'minac' and 'maxac' in armor.txt are both equal. Defense on all base armor types are always same. Can you please elaborate what actually wrong for you ?

**Comment by mapron** [comment]
Just for the record, it won't change items you already obtain. You need to shop / gamble / drop new item, existing items in the inventory can not be modified. It's how the game works.

**Comment by host1126** [comment]
![1](https://user-images.githubusercontent.com/24352145/215311335-18188da3-2cc3-40d1-aca5-3e1452d567ce.jpg)
![2](https://user-images.githubusercontent.com/24352145/215311342-6f748efb-5b54-499b-b02b-d9c2f8acf4d6.jpg)

This is a file created in the excel folder when set as shown in the picture in the Perfect rolls tab. The amor.txt file is not created. I'm playing legacy.

**Comment by mapron** [comment]
>  I'm playing legacy.

Thanks, for clarification. That's interesting. Is it vanilla LoD 1.14d or some mods?

**Comment by host1126** [comment]
This is vanilla LoD 1.13c

**Comment by mapron** [comment]
I see, yeah, I can reproduce that. Armor.txt missing on vanilla, but works in pd2, interesting. I will look what's the problem.

**Comment by mapron** [comment]
I fixed this, new release will come in a minute.

**Comment by mapron** [comment]
You can now download new release.
I also noticed rando is kinda broken for now for legacy, sorry for that. Not sure if I have time to fix it.
