### ISSUE TITLE
Generate Button creates only an more or less Empty mod.

### ISSUE THREAD

**Issue by PatrickZehentbauer** [mapron/d2modgen#16]
When creating a mod with this it only creates the path and file:
"Diablo II Resurrected\mods\randomizer\randomizer.mpq\data\global\excel\weapons.txt" which is empty.
Trying to run the game gives an error "an exception occurred" and the window closes.
The Button to create all .txt files should create a big list no? It also does nothing.

I tried the latest and the 0.5.7 version.
Running the program as administrator does not help.

**Comment by mapron** [comment]
Hi, please tell which D2 base data are you using? D2R or LoD 1.14d? Do you use any other mods in pre-gen? Would be nice if you attach your config (file-browse to settings folder- config.json)

**Comment by mapron** [comment]
no info provided, closing.
