### ISSUE TITLE
No terror zones?

### ISSUE THREAD

**Issue by jDub19x** [mapron/d2modgen#18]
Are there no terror zones or did i not use the correct file path maybe?

**Comment by mapron** [comment]
terror zones are available in single player after you beat baal on each difficulty. No need for mod for that functionality.

**Comment by jDub19x** [comment]
ya I did but they dont activate on any difficulty for some reason

**Comment by mapron** [comment]
Try to click gear button near 'play' and see if terror zones enabled there.
