### ISSUE TITLE
Feature: Quality of life tab.

### ISSUE THREAD

**Issue by mapron** [mapron/d2modgen#6]
Some folks really used QoL features from d2mm. So what should not take long:
- Add Horadric Cube as starter;
- Increase books size (i think 3x would be ok).

**Comment by WolfieeifloW** [comment]
Possibly increase Quivers and/or keys as well.

**Comment by mapron** [comment]
for quivers and keys mb differrent option then? Me in person believe it's totally ok as it is (I remember 150 quivers and 6 keys in classic)

**Comment by mapron** [comment]
RemoveUniqCharmLimit also nice to port, with randomizer you can have 10 differend Gheeds in the inventory.

**Comment by mapron** [comment]
Also add "lower Str/Dex requirements" slider.
